### ISSUE TITLE
Does not work with multi-language module

### ISSUE THREAD

**Issue by der-On** [blakeembrey/metalsmith-pagination#10]
Pagination is not aware of the locale property in page metadata.

I'm not sure how to solve this without breaking the current api as we do not have access to anything then the pagination properties when defining options like first and path.

**Comment by blakeembrey** [comment]
I don't understand the question or statement. Can you provide an example?

**Comment by der-On** [comment]
I've fixed the problem by using pagination once for each language with correctly prefixed paths and provding the correct `locale` property in the `pageMetadata` option.

``` javascript
// default locale
.use(pagination({
    'collections.posts': {
      perPage: 5,
      layout: 'blog_index.html.swig',
      first: 'blog/index.html',
      path: 'blog/page/:num/index.html',
      pageMetadata: {
        title: 'Blog'
      },
      filter: function (page) {
        return !page.private;
      }
    }
  }))
// 'en' locale
  .use(pagination({
    'collections.posts': {
      perPage: 5,
      layout: 'blog_index.html.swig',
      first: 'en/blog/index.html',
      path: 'en/blog/page/:num/index.html',
      pageMetadata: {
        title: 'Blog',
        locale: 'en'
      },
      filter: function (page) {
        return !page.private;
      }
    }
  }))
```

**Comment by blakeembrey** [comment]
Thanks for the snippet. I'd love to make this easier for you and understand how you're using i18n here. How would the i18n information be passed around? Is this for rendering i18n pages? I think you're on the right track then, you could even generate it on a loop (assuming I understand it now).

``` js
[null, 'en'].forEach(function (locale) {
  var prefix = locale ? locale + '/' : ''
  .use(pagination({
    'collections.posts': {
      perPage: 5,
      layout: 'blog_index.html.swig',
      first: prefix + 'blog/index.html',
      path: prefix + 'blog/page/:num/index.html',
      pageMetadata: {
        title: 'Blog',
        locale: locale
      },
      filter: function (page) {
        return !page.private;
      }
    }
  }))
})
```

I'd love to understand a little more though to see if this could be made easier for you.
