### ISSUE TITLE
Cannot output perPage limited article list using Handlebars templates

### ISSUE THREAD

**Issue by 1Copenut** [blakeembrey/metalsmith-pagination#11]
I must be doing something wrong, but can't see what. I'm following the instructions from your article on building a blog with Metalsmith, but using Handlebars over Jade: http://blakeembrey.com/articles/2014/09/building-a-blog-with-metalsmith/

Here's the relevant code, first from build.js:

``` javascript
Metalsmith(__dirname)
    .source('src')
    .use(collections({
        articles: {
            pattern: 'articles/**/*.md',
            sortBy: 'date',
            reverse: true
        },
        pages: {
            pattern: 'pages/**/*.md',
        }
    }))
    .use(pagination({
        'collections.articles': {
            'perPage': 2,
            'template': 'partials/blogNavigation.hbt',
            'path': 'page/:num/index.html'
        }
    }))
    .use(markdown({
        'smartypants': true,
        'gfm': true,
        'tables': true
    }))
    .use(permalinks())
    .use(templates('handlebars'))
    .destination('build')
    .build(function(err) {
        if (err) console.log(err);
    });
```

and the Handlebars template:

``` javascript
<h2 id="blogHeading">Top Blog Posts</h2>
<ul class="articleList">
    {{#each collections.articles}}
        <li class="articleList__item">
            <h3 class="articleList__itemName">
                <a href="{{ this.path }}">{{ this.title }}</a>
            </h3>
        </li>
    {{/each}}
</ul>
```

I've split the iterator for blog post headers into its own template, that rolls into the home.hbt that renders the index.html page, but cannot get the list to generate unless I use collections.articles. I'm not sure what to replace that with in Handlebars, and thus can't get my pagination or per page limiting in place.

**Comment by blakeembrey** [comment]
@1Copenut Do you have access to `pagination.files` - change `collections.articles` to `pagination.files`? Do you have the code that isn't working for you that I can see/try? A repro would be great too, if that doesn't work.

**Comment by 1Copenut** [comment]
Hi @blakeembrey 
I tried switching the collections.articles to pagination.files, but it doesn't output anything when I do.

Repo for my project: https://github.com/1Copenut/seward-fast/tree/feature/collections

I'll continue investigating on this end as well. 

Thank you.

**Comment by blakeembrey** [comment]
@1Copenut It appears to be working for me, I just added pagination and updated the template - what file output are you looking at?

**Comment by blakeembrey** [comment]
**templates/partials/blogNavigation.hbt**

``` hbs
<h2 id="blogHeading">Top Blog Posts</h2>
<ul class="articleList">
    {{#each pagination.files}}
        <li class="articleList__item">
            <h3 class="articleList__itemName">
                <a href="{{ this.path }}">{{ this.title }}</a>
            </h3>
        </li>
    {{/each}}
</ul>
```

**build.js**

``` js
    .use(pagination({
        'collections.articles': {
            'perPage': 2,
            'template': 'partials/blogNavigation.hbt',
            'path': 'page/:num/index.html'
        }
    }))
```

**build/page/1/index.html**

``` html
<h2 id="blogHeading">Top Blog Posts</h2>
<ul class="articleList">
        <li class="articleList__item">
            <h3 class="articleList__itemName">
                <a href="articles/2016-01-10-first-post">Example title.</a>
            </h3>
        </li>
</ul>
```

**Comment by 1Copenut** [comment]
Hm. I might just be mis-understanding how it works. I was expecting to see the perPage limited number of posts on the index.html front page, but seeing your example code, I can understand what's happening.

Sorry for the confusion, and thank you for help!

**Comment by blakeembrey** [comment]
@1Copenut If you want a different front-page, there's an option to change where the first page is output to.

Edit: https://github.com/blakeembrey/metalsmith-pagination#javascript (`first` option, you'll need to do some custom rendering if you want to make it look different though based on the current page number).
