### ISSUE TITLE
Please add template examples.

### ISSUE THREAD

**Issue by michaelkornblum** [blakeembrey/metalsmith-pagination#13]
Conceptually I like the idea of the plugin. But I'd really like to see an example of how it would be implemented in a jade template.

**Comment by blakeembrey** [comment]
What do you want to see? The `for` loop? If you know how to do that in your target template language, then you should have no problem :+1: Maybe http://blakeembrey.com/articles/2014/09/building-a-blog-with-metalsmith/#pagination will help?

**Comment by michaelkornblum** [comment]
Actually, that link sufficed nicely :) Thank you for you time in responding
to this issue. I'm actually about to give a presentation about static site
generators and wanted to feature your plugin. This little bit of
documentation is what I needed for my code example. Have a great day.

**Comment by blakeembrey** [comment]
@michaelkornblum Awesome, I'll try to copy some of the specifics in an abstract enough way into the README :smile:
