### ISSUE TITLE
add page metadata to pagination.files

### ISSUE THREAD

**Issue by ninjasort** [blakeembrey/metalsmith-pagination#15]
I'm trying to render a paginated collection with metadata added to each file from another plugin (excerpts).. Currently, it's not being added to each pagination.files metadata. The problem is that I can't access metalsmith with my current project as it's being abstracted away from a config so I don't have access to the metadata() to assign to fileMetadata. Is there any way that you can simply extend the files with the current file metadata in the collection assigned? That way the metadata property wouldn't be needed for pagination.files?

**Comment by 2pha** [comment]
Did you work out how to do it? I have the same question
