### ISSUE TITLE
Plugin creates index.html files, but there is no content in them

### ISSUE THREAD

**Issue by vortex6688** [blakeembrey/metalsmith-pagination#18]
Hello, i have a little issue here....

So i have 4 posts and plugin created 4 folders for me, but the index.html files in them are empty by some reason, Could you please tell me what the problem can be, i just need to get output in the generated index files. Let me know if you need anything else to determine the issue. Thank you! 

**1) I installed the plugin**
**2) Added plugin to my plugin list :** 

```
"metalsmith-pagination": {
      "collections.posts": {
        "perPage": 1,
        "layout": "blog.hbt",
        "path": "page:num/index.html"
      }
    }
```

**3) These are my collections:**

```
"metalsmith-collections": {
        "page": {
            "pattern": "**/index.*",
            "sortBy": "priority",
            "reverse": true,
            "refer": false,
            "metadata": {
                "layout": "page.hbt"
            }
        },
        "posts": {
            "sortBy": "publishDate",
            "reverse": true
        }
    }
```

**4) Here is the posts files' metadata:**

```

---
title: First Post
publishDate: 2014-04-18
layout: post.hbt
collection: posts

---

```

**5) Here is my blog.hbt layout:**

```
{{> header}}

<h2> This heading should be copied in every paginated page </h2>

{{> footer}}

```

**6) Here are the layouts and partials registered:** 

```
"metalsmith-layouts": {
        "engine": "handlebars",
        "directory": "src/website/layouts",
        "partials": "src/website/layouts/partials"
    },
    "metalsmith-in-place": {
      "engine": "handlebars",
      "partials": "src/website/layouts/partials"
    }
```

**Comment by blakeembrey** [comment]
This plugin must run before layouts and after the collection exists. If I had to guess, the layout is running before the files are generated.

**Comment by vortex6688** [comment]
it helped, thank you very much!
Sorry i bothered you about this....

**Comment by blakeembrey** [comment]
It's ok, I'm glad that worked. I'll check and make sure it's documented on the README 😄
