### ISSUE TITLE
Not overwriting files

### ISSUE THREAD

**Issue by ninjasort** [blakeembrey/metalsmith-pagination#21]
I'm trying to run this plugin after metalsmith-permalinks renders a set of posts. It used to work, but I've changed some of the metadata and it's not overwriting the file. Any thoughts?

```
Error: Failed to write the file at: dist/blog/2016/07/18/how-to-set-smart-marketing-goals-and-forecast-revenue/index.html

EEXIST: file already exists, mkdir /dist/blog/2016/07/18/how-to-set-smart-marketing-goals-and-forecast-revenue'
    at Error (native)
```

**Comment by blakeembrey** [comment]
This is not a problem for this plugin. Please read the Metalsmith documentation.
