### ISSUE TITLE
I can't get your plugin to work

### ISSUE THREAD

**Issue by ninjasort** [blakeembrey/metalsmith-pagination#22]
I've tried everything, it's not working..

```
  "pagination": {
    "collections.posts": {
      "perPage": 2,
      "first": "blog/index.html",
      "path": "blog/:num/index.html",
      "pageMetadata": {
"title": "Blog"
},
      "layout": "blog.liquid"
    }
  },
```

**Comment by ninjasort** [comment]
Please help here. The plugin is just flat out strange.

**Comment by blakeembrey** [comment]
You need to provide more information. Otherwise this will just be ignored. What is your Metalsmith configuration? Do you actually have a layout plugin? Provide a link to a demo.

**Comment by ninjasort** [comment]
I'm using the permalinks plugin and it's overwriting the path. If I want this path for posts:
`blog/2016/08/32/post-title-here`, and still each page to be `blog/page/1/`, `blog/page/2/`. What's the best way to configure that?

**Comment by blakeembrey** [comment]
Have you read other closed issues? For example, https://github.com/blakeembrey/metalsmith-pagination/issues/18?

**Comment by blakeembrey** [comment]
Use `blog/page/:num/index.html`?

**Comment by ninjasort** [comment]
Okay, but it doesn't for other permalinks to be used on the collection items. For example, using:

```
{
        "match": { "collection": "posts" },
        "pattern": "blog/:date/:title"
      },
```

after that point removes the 1, 2, folders entirely and replaces with the year only.

**Comment by blakeembrey** [comment]
I don't know what the configuration is for. It's not for this plugin.

**Comment by ninjasort** [comment]
Closing for now: https://github.com/segmentio/metalsmith-permalinks/issues/60

**Comment by ninjasort** [comment]
So when I create this configuration:

```
"pagination": {
    "collections.posts": {
      "perPage": 2,
      "first": "blog/index.html",
      "path": "blog/:num/index.html",
      "layout": "blog.liquid"
    }
  },
```

It creates an index page at `blog/index.html` but it uses the first post.

What I need is a blog index page with the pagination.files there.

**Comment by blakeembrey** [comment]
I really don't understand the problem. Have you actually created a template that renders the pagination files or are you just expecting it to already exist? Can you create a reproduction?

**Comment by ninjasort** [comment]
I'm using liquid yes. I've created `blog.liquid` but it doesn't render. Doesn't this plugin render the index page with the selected layout?

**Comment by ninjasort** [comment]
Any ideas? Literally just wanting to render the front blog page to loop through the files..

**Comment by ninjasort** [comment]
![screen shot 2016-08-23 at 10 18 46 pm](https://cloud.githubusercontent.com/assets/1614348/17916245/957a621c-697f-11e6-8dbc-c29f9a8e6cc2.png)

**Comment by ninjasort** [comment]
![screen shot 2016-08-23 at 10 19 03 pm](https://cloud.githubusercontent.com/assets/1614348/17916252/a23e6110-697f-11e6-8f7e-03a3efe7d76b.png)

**Comment by ninjasort** [comment]
Output
![screen shot 2016-08-23 at 10 19 34 pm](https://cloud.githubusercontent.com/assets/1614348/17916259/b20900c8-697f-11e6-81cc-9c8aef57cb46.png)

**Comment by ninjasort** [comment]
This is `blog.liquid`. The index page on `/blog` ends up rendering a single post, no pagination files to be found.

![screen shot 2016-08-23 at 10 20 49 pm](https://cloud.githubusercontent.com/assets/1614348/17916277/df9411b8-697f-11e6-87e3-e83479527c69.png)

**Comment by ninjasort** [comment]
Any answer tonight would be awesome.

**Comment by blakeembrey** [comment]
No, it doesn't render it for you. You need to have whatever layout plugin your using set up for this.

Some of us have jobs and live in different timezones, you can't expect a response all day (it's only 12.30pm here). I also gave you a perfectly working example months ago when you asked - see your previous issues https://github.com/blakeembrey/metalsmith-pagination/issues/12 and https://github.com/blakeembrey/metalsmith-pagination/issues/7. Out of the issues in this repo, half are yours. I won't be answering anymore.

**Comment by blakeembrey** [comment]
It does say this in the documentation too - https://github.com/blakeembrey/metalsmith-pagination#options. I was just about to try and update it in case that was causing confusion, but it seems clear enough to me. You need to be using a template plugin **after** this module (which is described in the issue I previously linked as well).
