### ISSUE TITLE
metalsmith-templates is deprecated. 

### ISSUE THREAD

**Issue by gl2748** [blakeembrey/metalsmith-pagination#24]
Per:
https://github.com/segmentio/metalsmith-templates  

```
Note: this plugin is deprecated, and was split into two simpler plugins:

metalsmith-layouts for rendering templates inside nested layouts.
metalsmith-in-place for render an individual file through a templating engine.
```

Plan to update docs accordingly.

**Comment by bnchdrff** [comment]
see https://github.com/blakeembrey/metalsmith-pagination/issues/17

**Comment by blakeembrey** [comment]
I'm don't think this is an issue here. There's no dependency, you just need to update the configuration seen in the README to use layouts or in-place.
