### ISSUE TITLE
Why is page 1 generated twice when options.first is set?

### ISSUE THREAD

**Issue by leonderijke** [blakeembrey/metalsmith-pagination#5]
As can be seen in the tests, when the `first` option is set, a `firstPage` and a `pageOne` are created:

``` js
        var firstPage = files['articles/index.html']
        var pageOne = files['articles/page/1/index.html']
        (...)
        expect(firstPage).to.exist
        expect(firstPage).to.not.equal(pageOne)
        expect(firstPage.pagination.next).to.equal(pageTwo)
        expect(firstPage.pagination.previous).to.not.exist

        expect(pageOne).to.exist
        expect(pageOne.pagination.next).to.equal(pageTwo)
        expect(pageOne.pagination.previous).to.not.exist
```

The contents of `firstPage` and `pageOne` are the same, so I'm wondering: why is `pageOne` created?

**Comment by blakeembrey** [comment]
@leonderijke When I wrote this, it was mostly for consistency. Since `firstPage` could be anything, I wanted a way for people to navigate back to page 1 easily without having to find it. E.g. Just replace `/page/2` with `/page/1`. So, personal preference. It may be worth adding canonical support for SEO cases, but do you have any other concerns?

**Comment by leonderijke** [comment]
SEO is indeed my primary concern. Although I find it a bit unusual to have two "page 1's". I'd prefer not generating `pageOne` when there is a `firstPage` over adding canonical support. What do you think?

**Comment by blakeembrey** [comment]
I'll add an option to disable `pageOne`, when you have a separate `firstPage` option enabled - it's easy enough to support.

**Comment by blakeembrey** [comment]
Added **noPageOne** option with [`v1.2.0`](https://github.com/blakeembrey/metalsmith-pagination/releases/tag/v1.2.0)
